---

- name: Install web server packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5
    - php5-cli
    - php5-curl
    - php5-imagick
    - php5-json   
    - php5-mcrypt

- name: enable apache modules
  shell: a2enmod rewrite deflate expires headers
  args:
    creates: /etc/apache2/mods-enabled/rewrite.load
    
- name: Install php igbinary
  shell: pecl install igbinary
  args:
    creates: /usr/lib/php5/20121212/igbinary.so

- name: enable php5 modules
  shell: php5enmod mcrypt curl igbinary
  args:
    creates: /etc/php5/apache2/conf.d/20-igbinary.ini

- name: install global composer binary
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
    
